/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Oskar
 */
public class View extends javax.swing.JFrame {

   private Engine silnik;
    public View() {
        
        initComponents();
        jp_Game.setVisible(false);
        jp_settings.setVisible(false);
        js_ileGraczy.setValue(2);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog = new javax.swing.JDialog();
        jl_logo = new javax.swing.JLabel();
        jl_autorzy = new javax.swing.JLabel();
        jl_dawid = new javax.swing.JLabel();
        jl_oskar = new javax.swing.JLabel();
        jl_pawel = new javax.swing.JLabel();
        jl_patryk = new javax.swing.JLabel();
        jb_zakoncz = new javax.swing.JButton();
        Jd_kupP = new javax.swing.JDialog();
        jL_kupP = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jD_kupD = new javax.swing.JDialog();
        jD_zaplac = new javax.swing.JDialog();
        jp_settings = new javax.swing.JPanel();
        jl_Ustawienia = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jb_Start = new javax.swing.JButton();
        jl_logoSettings = new javax.swing.JLabel();
        jcb_graNaCzas = new javax.swing.JCheckBox();
        js_ileGraczy = new javax.swing.JSpinner();
        jcb_gracz1 = new javax.swing.JComboBox<>();
        jcb_gracz2 = new javax.swing.JComboBox<>();
        jcb_gracz3 = new javax.swing.JComboBox<>();
        jcb_gracz4 = new javax.swing.JComboBox<>();
        jl_iloscGraczy = new javax.swing.JLabel();
        jT_gracz1 = new javax.swing.JTextField();
        jT_gracz2 = new javax.swing.JTextField();
        jT_gracz3 = new javax.swing.JTextField();
        jT_gracz4 = new javax.swing.JTextField();
        jp_Game = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        card_View1 = new Card_View();
        jp_start = new javax.swing.JPanel();
        jb_Start1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jm_plik = new javax.swing.JMenu();
        jmi_wczytaj = new javax.swing.JMenuItem();
        jmi_zakoncz = new javax.swing.JMenuItem();
        jm_pomoc = new javax.swing.JMenu();
        jmi_autorzy = new javax.swing.JMenuItem();

        jDialog.setSize(new java.awt.Dimension(600, 600));

        jl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jl_logo.setText("jLabel14");

        jl_autorzy.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jl_autorzy.setText("Autorzy:");

        jl_dawid.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jl_dawid.setText("Dawid Gawiński");

        jl_oskar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jl_oskar.setText("Oskar Gruszczyński");

        jl_pawel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jl_pawel.setText("Paweł Gawron");

        jl_patryk.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jl_patryk.setText("Patryk Afelt");

        jb_zakoncz.setText("Zakończ");
        jb_zakoncz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_zakonczActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogLayout = new javax.swing.GroupLayout(jDialog.getContentPane());
        jDialog.getContentPane().setLayout(jDialogLayout);
        jDialogLayout.setHorizontalGroup(
            jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogLayout.createSequentialGroup()
                .addGroup(jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_dawid)
                            .addGroup(jDialogLayout.createSequentialGroup()
                                .addComponent(jl_autorzy, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))))
                    .addGroup(jDialogLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_pawel)
                            .addComponent(jl_oskar)
                            .addGroup(jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jb_zakoncz, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jl_patryk, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jDialogLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jDialogLayout.setVerticalGroup(
            jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_logo)
                .addGap(18, 18, 18)
                .addComponent(jl_autorzy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_dawid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_oskar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_pawel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_patryk)
                .addGap(39, 39, 39)
                .addComponent(jb_zakoncz, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        Jd_kupP.setTitle("Kup Pole");
        Jd_kupP.setMinimumSize(new java.awt.Dimension(333, 200));

        jL_kupP.setText("Czy chcesz kupic?");

        jButton2.setText("Tak");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Nie");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Jd_kupPLayout = new javax.swing.GroupLayout(Jd_kupP.getContentPane());
        Jd_kupP.getContentPane().setLayout(Jd_kupPLayout);
        Jd_kupPLayout.setHorizontalGroup(
            Jd_kupPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jd_kupPLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addComponent(jL_kupP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Jd_kupPLayout.setVerticalGroup(
            Jd_kupPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jd_kupPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_kupP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Jd_kupPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jD_kupDLayout = new javax.swing.GroupLayout(jD_kupD.getContentPane());
        jD_kupD.getContentPane().setLayout(jD_kupDLayout);
        jD_kupDLayout.setHorizontalGroup(
            jD_kupDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jD_kupDLayout.setVerticalGroup(
            jD_kupDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jD_zaplacLayout = new javax.swing.GroupLayout(jD_zaplac.getContentPane());
        jD_zaplac.getContentPane().setLayout(jD_zaplacLayout);
        jD_zaplacLayout.setHorizontalGroup(
            jD_zaplacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jD_zaplacLayout.setVerticalGroup(
            jD_zaplacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("University Monopoly");
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));

        jp_settings.setPreferredSize(new java.awt.Dimension(1366, 768));

        jl_Ustawienia.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jl_Ustawienia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Ustawienia.setText("Ustawienia");
        jl_Ustawienia.setToolTipText("");

        jb_Start.setText("Start");
        jb_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_StartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(572, 572, 572))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jl_logoSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jl_logoSettings.setText(null);
        jl_logoSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jcb_graNaCzas.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jcb_graNaCzas.setText("Gra na czas");
        jcb_graNaCzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_graNaCzasActionPerformed(evt);
            }
        });

        js_ileGraczy.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                js_ileGraczyStateChanged(evt);
            }
        });

        jcb_gracz1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gracz1", "Gracz2", "Gracz3", "Gracz4" }));

        jcb_gracz2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gracz1", "Gracz2", "Gracz3", "Gracz4" }));

        jcb_gracz3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gracz1", "Gracz2", "Gracz3", "Gracz4" }));

        jcb_gracz4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gracz1", "Gracz2", "Gracz3", "Gracz4" }));

        jl_iloscGraczy.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jl_iloscGraczy.setText("Podaj liczbę graczy (2 - 4 osoby)");

        jT_gracz1.setText("Gracz1");

        jT_gracz2.setText("Gracz2");

        jT_gracz3.setText("Gracz3");

        jT_gracz4.setText("Gracz4");

        javax.swing.GroupLayout jp_settingsLayout = new javax.swing.GroupLayout(jp_settings);
        jp_settings.setLayout(jp_settingsLayout);
        jp_settingsLayout.setHorizontalGroup(
            jp_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_settingsLayout.createSequentialGroup()
                .addGroup(jp_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_settingsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jp_settingsLayout.createSequentialGroup()
                        .addGap(0, 298, Short.MAX_VALUE)
                        .addComponent(jl_Ustawienia, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(jl_logoSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jp_settingsLayout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addGroup(jp_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcb_graNaCzas, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_settingsLayout.createSequentialGroup()
                        .addComponent(js_ileGraczy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jl_iloscGraczy))
                    .addGroup(jp_settingsLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jp_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jT_gracz1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_gracz3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jp_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcb_gracz1, 0, 87, Short.MAX_VALUE)
                            .addComponent(jcb_gracz2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(236, 236, 236)
                        .addGroup(jp_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jT_gracz4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_gracz2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jp_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_settingsLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jcb_gracz3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_settingsLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jcb_gracz4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_settingsLayout.setVerticalGroup(
            jp_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_settingsLayout.createSequentialGroup()
                .addGroup(jp_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_logoSettings)
                    .addGroup(jp_settingsLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jl_Ustawienia, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addComponent(jcb_graNaCzas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jp_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_ileGraczy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_iloscGraczy))
                .addGroup(jp_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_settingsLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jp_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcb_gracz1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_gracz1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp_settingsLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jp_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcb_gracz3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_gracz2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(76, 76, 76)
                .addGroup(jp_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_settingsLayout.createSequentialGroup()
                        .addGroup(jp_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcb_gracz2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_gracz3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_settingsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jp_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcb_gracz4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_gracz4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108)))
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        jp_Game.setPreferredSize(new java.awt.Dimension(1366, 768));

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 768));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly.PNG"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setMaximumSize(new java.awt.Dimension(701, 700));
        jLabel1.setMinimumSize(new java.awt.Dimension(701, 733));
        jLabel1.setPreferredSize(new java.awt.Dimension(701, 700));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 701, 733);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Gracz 1");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("3000$");

        jButton1.setBackground(java.awt.SystemColor.controlShadow);
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Rzuc Kostkami");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("Handel");

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Koniec Tury");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(17, 17, 17))
        );

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Fundsze:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Gracz 1");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Gracz 2");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Gracz 3");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Gracz 4");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("3000$");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("3000$");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("3000$");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("3000$");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel12))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp_GameLayout = new javax.swing.GroupLayout(jp_Game);
        jp_Game.setLayout(jp_GameLayout);
        jp_GameLayout.setHorizontalGroup(
            jp_GameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_GameLayout.createSequentialGroup()
                .addContainerGap(736, Short.MAX_VALUE)
                .addGroup(jp_GameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_GameLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_GameLayout.createSequentialGroup()
                        .addComponent(card_View1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(347, 347, 347))))
            .addGroup(jp_GameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_GameLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(655, Short.MAX_VALUE)))
        );
        jp_GameLayout.setVerticalGroup(
            jp_GameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_GameLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(card_View1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
            .addGroup(jp_GameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_GameLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jp_start.setBackground(new java.awt.Color(255, 255, 255));
        jp_start.setPreferredSize(new java.awt.Dimension(1366, 768));

        jb_Start1.setBackground(java.awt.Color.gray);
        jb_Start1.setText("Start");
        jb_Start1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_Start1ActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jLabel15.setText(null);
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jp_startLayout = new javax.swing.GroupLayout(jp_start);
        jp_start.setLayout(jp_startLayout);
        jp_startLayout.setHorizontalGroup(
            jp_startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_startLayout.createSequentialGroup()
                .addGap(565, 565, 565)
                .addGroup(jp_startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_Start1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_startLayout.setVerticalGroup(
            jp_startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_startLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_Start1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );

        jm_plik.setText("Plik");

        jmi_wczytaj.setText("Wczytaj");
        jm_plik.add(jmi_wczytaj);

        jmi_zakoncz.setText("Zakończ");
        jmi_zakoncz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_zakonczActionPerformed(evt);
            }
        });
        jm_plik.add(jmi_zakoncz);

        jMenuBar.add(jm_plik);

        jm_pomoc.setText("Pomoc");

        jmi_autorzy.setText("o Autorach");
        jmi_autorzy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_autorzyActionPerformed(evt);
            }
        });
        jm_pomoc.add(jmi_autorzy);

        jMenuBar.add(jm_pomoc);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_Game, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp_settings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jp_start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jp_Game, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jp_settings, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jp_start, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        silnik.random2k6();
        jTextArea1.setText(silnik.getLog());
        jButton1.setEnabled(false);
        jButton3.setEnabled(true);
        
        if (silnik.getPole(silnik.getGracze(silnik.getIdAktywny()).getWhere()).getOwner()=="oskar")
        {
            jL_kupP.setText("Czy chcesz kupic " + silnik.getPole(silnik.getGracze(silnik.getIdAktywny()).getWhere()).getName()+"?");
            Jd_kupP.setVisible(true);
            
        }
        
        if (silnik.getPole(silnik.getGracze(silnik.getIdAktywny()).getWhere()).getOwner()==silnik.getGracze(silnik.getIdAktywny()).getName());
        {
            
        }
        
        if (silnik.getPole(silnik.getGracze(silnik.getIdAktywny()).getWhere()).getOwner()!=silnik.getGracze(silnik.getIdAktywny()).getName() && silnik.getPole(silnik.getGracze(silnik.getIdAktywny()).getWhere()).getOwner()!="oskar")
        {
            
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       silnik.koniecTury();
       jTextArea1.setText(silnik.getLog());
       jButton1.setEnabled(true);
       jButton3.setEnabled(false);
       jLabel2.setText(silnik.getAktywnyPlayer().getName());
       jLabel3.setText(silnik.getAktywnyPlayer().getMoney().toString());
       
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jcb_graNaCzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_graNaCzasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_graNaCzasActionPerformed

    private void jb_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_StartActionPerformed
        jp_settings.setVisible(false);   
        jp_Game.setVisible(true);
        if(Integer.parseInt(js_ileGraczy.getValue().toString())==2)
        {
            silnik = new Engine(Integer.parseInt(js_ileGraczy.getValue().toString()),jT_gracz1.getText(),jcb_gracz1.getSelectedItem().toString(),jT_gracz2.getText(),jcb_gracz3.getSelectedItem().toString());
            jLabel5.setVisible(true);
            jLabel5.setText(jT_gracz1.getText());
            jLabel6.setVisible(true);
            jLabel6.setText(jT_gracz2.getText());
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jLabel9.setText(silnik.getGracze(0).getMoney().toString());
            jLabel10.setText(silnik.getGracze(1).getMoney().toString());
            jLabel11.setVisible(false);
            jLabel12.setVisible(false);
                    
        }
        if(Integer.parseInt(js_ileGraczy.getValue().toString())==3)
        {
            silnik = new Engine(Integer.parseInt(js_ileGraczy.getValue().toString()),jT_gracz1.getText(),jcb_gracz1.getSelectedItem().toString(),jT_gracz2.getText(),jcb_gracz3.getSelectedItem().toString(),jT_gracz3.getText(),jcb_gracz2.getSelectedItem().toString());
            jLabel5.setVisible(true);
            jLabel5.setText(jT_gracz1.getText());
            jLabel6.setVisible(true);
            jLabel6.setText(jT_gracz2.getText());
            jLabel7.setVisible(true);
            jLabel7.setText(jT_gracz3.getText());
            jLabel9.setText(silnik.getGracze(0).getMoney().toString());
            jLabel10.setText(silnik.getGracze(1).getMoney().toString());
            jLabel11.setText(silnik.getGracze(2).getMoney().toString());
            
            jLabel8.setVisible(false);
            jLabel12.setVisible(false);
        }
        if(Integer.parseInt(js_ileGraczy.getValue().toString())==4)
        {
            silnik = new Engine(Integer.parseInt(js_ileGraczy.getValue().toString()),jT_gracz1.getText(),jcb_gracz1.getSelectedItem().toString(),jT_gracz2.getText(),jcb_gracz3.getSelectedItem().toString(),jT_gracz3.getText(),jcb_gracz2.getSelectedItem().toString(),jT_gracz4.getText(),jcb_gracz4.getSelectedItem().toString());
            jLabel5.setVisible(true);
            jLabel5.setText(jT_gracz1.getText());
            jLabel6.setVisible(true);
            jLabel6.setText(jT_gracz2.getText());
            jLabel7.setVisible(true);
            jLabel7.setText(jT_gracz3.getText());
            jLabel8.setVisible(true);
            jLabel8.setText(jT_gracz4.getText());
            jLabel9.setText(silnik.getGracze(0).getMoney().toString());
            jLabel10.setText(silnik.getGracze(1).getMoney().toString());
            jLabel11.setText(silnik.getGracze(2).getMoney().toString());
            jLabel12.setText(silnik.getGracze(3).getMoney().toString());
            
        }
        jLabel2.setText(silnik.getAktywnyPlayer().getName());
        jLabel3.setText(silnik.getAktywnyPlayer().getMoney()+"");
        jTextArea1.setText(silnik.getLog());
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
                
    }//GEN-LAST:event_jb_StartActionPerformed

    private void jb_Start1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_Start1ActionPerformed
        jp_start.setVisible(false);
        jp_settings.setVisible(true);
        jT_gracz3.setVisible(false);
        jT_gracz4.setVisible(false);
        jcb_gracz2.setVisible(false);
        jcb_gracz4.setVisible(false);
        
        jcb_gracz1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Czerwony", "Niebieski","Zielony","Żółty" }));
         jcb_gracz2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Czerwony", "Niebieski","Zielony","Żółty" }));
        jcb_gracz3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Czerwony", "Niebieski","Zielony","Żółty" }));
         jcb_gracz4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Czerwony", "Niebieski","Zielony","Żółty" }));
       
    }//GEN-LAST:event_jb_Start1ActionPerformed

    private void jb_zakonczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_zakonczActionPerformed
       jDialog.setVisible(false);
    }//GEN-LAST:event_jb_zakonczActionPerformed

    private void jmi_autorzyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_autorzyActionPerformed
        jDialog.setVisible(true);
    }//GEN-LAST:event_jmi_autorzyActionPerformed

    private void jmi_zakonczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_zakonczActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jmi_zakonczActionPerformed

    private void js_ileGraczyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_js_ileGraczyStateChanged
       if(Integer.parseInt(js_ileGraczy.getValue().toString())<2)
        {
            js_ileGraczy.setValue(2);
        }
        if (Integer.parseInt(js_ileGraczy.getValue().toString())>4)
        {
            js_ileGraczy.setValue(4);
        }
        if (Integer.parseInt(js_ileGraczy.getValue().toString())==2)
        {
            jcb_gracz2.setVisible(false);
            jcb_gracz4.setVisible(false);
            jT_gracz3.setVisible(false);
            jT_gracz4.setVisible(false);
           
        }
        if (Integer.parseInt(js_ileGraczy.getValue().toString())==3)
        {
            jcb_gracz2.setVisible(true);
            jT_gracz3.setVisible(true);
            jcb_gracz4.setVisible(false);
            jT_gracz4.setVisible(false);
            
        }
         if (Integer.parseInt(js_ileGraczy.getValue().toString())==4)
        {
            
            jcb_gracz4.setVisible(true);
            jT_gracz4.setVisible(true);
          
        }
    }//GEN-LAST:event_js_ileGraczyStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Jd_kupP.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Jd_kupP.setVisible(false);
       silnik.getPole(silnik.getGracze(silnik.getIdAktywny()).getWhere()).setOwner(silnik.getGracze(silnik.getIdAktywny()).getName());
       silnik.getGracze(silnik.getIdAktywny()).setMoney(silnik.getGracze(silnik.getIdAktywny()).getMoney()-silnik.getPole(silnik.getGracze(silnik.getIdAktywny()).getWhere()).getBuy_out());        
       silnik.setLog(silnik.getLog()+"\n"+silnik.getGracze(silnik.getIdAktywny()).getName()+" Kupil "+ silnik.getPole(silnik.getGracze(silnik.getIdAktywny()).getWhere()).getName());
       silnik.getAktywnyPlayer().addToHand(silnik.getPole(silnik.getGracze(silnik.getIdAktywny()).getWhere()).getID());
       jLabel3.setText(silnik.getAktywnyPlayer().getMoney().toString());
       jTextArea1.setText(silnik.getLog());
       
       
       
       
       
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Jd_kupP;
    private Card_View card_View1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDialog jD_kupD;
    private javax.swing.JDialog jD_zaplac;
    private javax.swing.JDialog jDialog;
    private javax.swing.JLabel jL_kupP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_gracz1;
    private javax.swing.JTextField jT_gracz2;
    private javax.swing.JTextField jT_gracz3;
    private javax.swing.JTextField jT_gracz4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jb_Start;
    private javax.swing.JButton jb_Start1;
    private javax.swing.JButton jb_zakoncz;
    private javax.swing.JCheckBox jcb_graNaCzas;
    private javax.swing.JComboBox<String> jcb_gracz1;
    private javax.swing.JComboBox<String> jcb_gracz2;
    private javax.swing.JComboBox<String> jcb_gracz3;
    private javax.swing.JComboBox<String> jcb_gracz4;
    private javax.swing.JLabel jl_Ustawienia;
    private javax.swing.JLabel jl_autorzy;
    private javax.swing.JLabel jl_dawid;
    private javax.swing.JLabel jl_iloscGraczy;
    private javax.swing.JLabel jl_logo;
    private javax.swing.JLabel jl_logoSettings;
    private javax.swing.JLabel jl_oskar;
    private javax.swing.JLabel jl_patryk;
    private javax.swing.JLabel jl_pawel;
    private javax.swing.JMenu jm_plik;
    private javax.swing.JMenu jm_pomoc;
    private javax.swing.JMenuItem jmi_autorzy;
    private javax.swing.JMenuItem jmi_wczytaj;
    private javax.swing.JMenuItem jmi_zakoncz;
    private javax.swing.JPanel jp_Game;
    private javax.swing.JPanel jp_settings;
    private javax.swing.JPanel jp_start;
    private javax.swing.JSpinner js_ileGraczy;
    // End of variables declaration//GEN-END:variables
}
