/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package umonopoly.v2;

import java.util.Vector;

/**
 *
 * @author Oskar
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    private Engine silnik;
    public MainWindow() {
        initComponents();
        jp_Ustawienia.setVisible(false);
        jp_Gra.setVisible(false);
        js_LiczbaGraczy.setValue(2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Autorzy = new javax.swing.JDialog();
        jl_Logo2 = new javax.swing.JLabel();
        jl_autorzy = new javax.swing.JLabel();
        jl_dawid = new javax.swing.JLabel();
        jl_oskar = new javax.swing.JLabel();
        jl_pawel = new javax.swing.JLabel();
        jl_patryk = new javax.swing.JLabel();
        jb_zakoncz = new javax.swing.JButton();
        jd_KupP = new javax.swing.JDialog();
        jl_KupP = new javax.swing.JLabel();
        jb_KupTak = new javax.swing.JButton();
        jb_KupNie = new javax.swing.JButton();
        jd_KupD = new javax.swing.JDialog();
        jl_KupD = new javax.swing.JLabel();
        jb_KupDTak = new javax.swing.JButton();
        jb_KupDNie = new javax.swing.JButton();
        jd_Error = new javax.swing.JDialog();
        jl_Error = new javax.swing.JLabel();
        jb_Error = new javax.swing.JButton();
        jd_Rachunek = new javax.swing.JDialog();
        jl_Rachunek = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jta_Rachunek = new javax.swing.JTextArea();
        jb_Zaplac = new javax.swing.JButton();
        jp_Gra = new javax.swing.JPanel();
        jp_Plansza = new javax.swing.JPanel();
        jl_Plansza = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtp_Log = new javax.swing.JTextPane();
        jl_AktywnyGracz = new javax.swing.JLabel();
        jb_Roll = new javax.swing.JButton();
        jb_Eot = new javax.swing.JButton();
        jl_Fundusze = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jta_Fundusze = new javax.swing.JTextArea();
        jp_Ustawienia = new javax.swing.JPanel();
        jl_Ustawienia = new javax.swing.JLabel();
        js_LiczbaGraczy = new javax.swing.JSpinner();
        jl_LiczbaGraczy = new javax.swing.JLabel();
        jtf_NazwaGracza1 = new javax.swing.JTextField();
        jtf_NazwaGracza2 = new javax.swing.JTextField();
        jtf_NazwaGracza3 = new javax.swing.JTextField();
        jtf_NazwaGracza4 = new javax.swing.JTextField();
        jcb_KolorGracza1 = new javax.swing.JComboBox<>();
        jcb_KolorGracza2 = new javax.swing.JComboBox<>();
        jcb_KolorGracza3 = new javax.swing.JComboBox<>();
        jcb_KolorGracza4 = new javax.swing.JComboBox<>();
        jb_StartGra = new javax.swing.JButton();
        jp_Start = new javax.swing.JPanel();
        jb_Start = new javax.swing.JButton();
        jb_Autorzy = new javax.swing.JButton();
        jl_Logo = new javax.swing.JLabel();

        jd_Autorzy.setTitle("Autorzy");
        jd_Autorzy.setMinimumSize(new java.awt.Dimension(310, 550));
        jd_Autorzy.setResizable(false);
        jd_Autorzy.setSize(new java.awt.Dimension(310, 550));

        jl_Logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umonopoly/v2/logo.png"))); // NOI18N

        jl_autorzy.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jl_autorzy.setText("Autorzy:");

        jl_dawid.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jl_dawid.setText("Dawid Gawiński");

        jl_oskar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jl_oskar.setText("Oskar Gruszczyński");

        jl_pawel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jl_pawel.setText("Paweł Gawron");

        jl_patryk.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jl_patryk.setText("Patryk Afelt");

        jb_zakoncz.setText("Zakończ");
        jb_zakoncz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_zakonczActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_AutorzyLayout = new javax.swing.GroupLayout(jd_Autorzy.getContentPane());
        jd_Autorzy.getContentPane().setLayout(jd_AutorzyLayout);
        jd_AutorzyLayout.setHorizontalGroup(
            jd_AutorzyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AutorzyLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jd_AutorzyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jl_autorzy, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_dawid)
                    .addComponent(jl_oskar)
                    .addComponent(jl_pawel)
                    .addComponent(jl_patryk)
                    .addComponent(jb_zakoncz, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Logo2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jd_AutorzyLayout.setVerticalGroup(
            jd_AutorzyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AutorzyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_Logo2)
                .addGap(18, 18, 18)
                .addComponent(jl_autorzy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_dawid)
                .addGap(11, 11, 11)
                .addComponent(jl_oskar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_pawel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_patryk)
                .addGap(36, 36, 36)
                .addComponent(jb_zakoncz, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jd_KupP.setTitle("Kup pole");
        jd_KupP.setMinimumSize(new java.awt.Dimension(420, 200));
        jd_KupP.setPreferredSize(new java.awt.Dimension(420, 200));

        jl_KupP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_KupP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_KupP.setText("Czy chcesz kupic?");

        jb_KupTak.setText("Tak");
        jb_KupTak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_KupTakActionPerformed(evt);
            }
        });

        jb_KupNie.setText("Nie");
        jb_KupNie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_KupNieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_KupPLayout = new javax.swing.GroupLayout(jd_KupP.getContentPane());
        jd_KupP.getContentPane().setLayout(jd_KupPLayout);
        jd_KupPLayout.setHorizontalGroup(
            jd_KupPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_KupPLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(jd_KupPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jl_KupP, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addGroup(jd_KupPLayout.createSequentialGroup()
                        .addComponent(jb_KupTak, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jb_KupNie, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );
        jd_KupPLayout.setVerticalGroup(
            jd_KupPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_KupPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_KupP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_KupPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_KupTak)
                    .addComponent(jb_KupNie))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jd_KupD.setTitle("Modernizacja");
        jd_KupD.setMinimumSize(new java.awt.Dimension(500, 200));

        jl_KupD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_KupD.setText("Czy chcesz kupic domek za 200$?");

        jb_KupDTak.setText("Tak");
        jb_KupDTak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_KupDTakActionPerformed(evt);
            }
        });

        jb_KupDNie.setText("Nie");
        jb_KupDNie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_KupDNieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_KupDLayout = new javax.swing.GroupLayout(jd_KupD.getContentPane());
        jd_KupD.getContentPane().setLayout(jd_KupDLayout);
        jd_KupDLayout.setHorizontalGroup(
            jd_KupDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_KupDLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(jd_KupDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jl_KupD)
                    .addGroup(jd_KupDLayout.createSequentialGroup()
                        .addComponent(jb_KupDTak)
                        .addGap(46, 46, 46)
                        .addComponent(jb_KupDNie)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jd_KupDLayout.setVerticalGroup(
            jd_KupDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_KupDLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jl_KupD)
                .addGap(43, 43, 43)
                .addGroup(jd_KupDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_KupDTak)
                    .addComponent(jb_KupDNie))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jd_Error.setTitle("Error");

        jl_Error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_Error.setText("Nie masz tyle pieniedzy!");

        jb_Error.setText("ok");
        jb_Error.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ErrorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_ErrorLayout = new javax.swing.GroupLayout(jd_Error.getContentPane());
        jd_Error.getContentPane().setLayout(jd_ErrorLayout);
        jd_ErrorLayout.setHorizontalGroup(
            jd_ErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ErrorLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jd_ErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jb_Error)
                    .addComponent(jl_Error))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jd_ErrorLayout.setVerticalGroup(
            jd_ErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ErrorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jl_Error)
                .addGap(18, 18, 18)
                .addComponent(jb_Error)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jd_Rachunek.setTitle("Rachunek");
        jd_Rachunek.setMinimumSize(new java.awt.Dimension(351, 212));

        jl_Rachunek.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_Rachunek.setText("Rachunek");

        jta_Rachunek.setColumns(20);
        jta_Rachunek.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jta_Rachunek.setRows(5);
        jta_Rachunek.setText("Od: Oskar\nDo: Oskar\nZa: szkola plebelbelebelbel\nNależnosc: ");
        jScrollPane3.setViewportView(jta_Rachunek);

        jb_Zaplac.setText("Zapłać");
        jb_Zaplac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ZaplacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_RachunekLayout = new javax.swing.GroupLayout(jd_Rachunek.getContentPane());
        jd_Rachunek.getContentPane().setLayout(jd_RachunekLayout);
        jd_RachunekLayout.setHorizontalGroup(
            jd_RachunekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_RachunekLayout.createSequentialGroup()
                .addGroup(jd_RachunekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_RachunekLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jd_RachunekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_Rachunek)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_RachunekLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jb_Zaplac)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jd_RachunekLayout.setVerticalGroup(
            jd_RachunekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_RachunekLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_Rachunek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_Zaplac)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UMonopoly 2.0");
        setMinimumSize(new java.awt.Dimension(1280, 1024));

        jp_Gra.setBackground(new java.awt.Color(0, 255, 255));

        jl_Plansza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umonopoly/v2/monopoly.PNG"))); // NOI18N

        javax.swing.GroupLayout jp_PlanszaLayout = new javax.swing.GroupLayout(jp_Plansza);
        jp_Plansza.setLayout(jp_PlanszaLayout);
        jp_PlanszaLayout.setHorizontalGroup(
            jp_PlanszaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_PlanszaLayout.createSequentialGroup()
                .addComponent(jl_Plansza)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jp_PlanszaLayout.setVerticalGroup(
            jp_PlanszaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_PlanszaLayout.createSequentialGroup()
                .addComponent(jl_Plansza)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jtp_Log.setEditable(false);
        jScrollPane1.setViewportView(jtp_Log);

        jl_AktywnyGracz.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_AktywnyGracz.setText("Aktywny gracz:");

        jb_Roll.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb_Roll.setText("Rzuć kostkami");
        jb_Roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_RollActionPerformed(evt);
            }
        });

        jb_Eot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb_Eot.setText("Skończ kolejke");
        jb_Eot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_EotActionPerformed(evt);
            }
        });

        jl_Fundusze.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_Fundusze.setText("Fundusze:");

        jta_Fundusze.setEditable(false);
        jta_Fundusze.setBackground(new java.awt.Color(0, 255, 255));
        jta_Fundusze.setColumns(20);
        jta_Fundusze.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jta_Fundusze.setLineWrap(true);
        jta_Fundusze.setRows(5);
        jScrollPane2.setViewportView(jta_Fundusze);

        javax.swing.GroupLayout jp_GraLayout = new javax.swing.GroupLayout(jp_Gra);
        jp_Gra.setLayout(jp_GraLayout);
        jp_GraLayout.setHorizontalGroup(
            jp_GraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_GraLayout.createSequentialGroup()
                .addComponent(jp_Plansza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_GraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jp_GraLayout.createSequentialGroup()
                        .addGroup(jp_GraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_AktywnyGracz, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp_GraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jb_Roll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jb_Eot, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jp_GraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_Fundusze)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 333, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jp_GraLayout.setVerticalGroup(
            jp_GraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_GraLayout.createSequentialGroup()
                .addGroup(jp_GraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_Plansza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_GraLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_GraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_AktywnyGracz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_Fundusze))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_GraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_GraLayout.createSequentialGroup()
                                .addComponent(jb_Roll)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_Eot))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 679, Short.MAX_VALUE))
        );

        jp_Ustawienia.setBackground(new java.awt.Color(255, 0, 255));
        jp_Ustawienia.setMinimumSize(new java.awt.Dimension(1280, 1024));
        jp_Ustawienia.setPreferredSize(new java.awt.Dimension(1280, 1024));

        jl_Ustawienia.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jl_Ustawienia.setText("Ustawienia");

        js_LiczbaGraczy.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                js_LiczbaGraczyStateChanged(evt);
            }
        });

        jl_LiczbaGraczy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_LiczbaGraczy.setText("Liczba graczy:");

        jtf_NazwaGracza1.setText("Gracz1");

        jtf_NazwaGracza2.setText("Gracz2");

        jtf_NazwaGracza3.setText("Gracz3");
        jtf_NazwaGracza3.setMaximumSize(new java.awt.Dimension(39, 20));
        jtf_NazwaGracza3.setMinimumSize(new java.awt.Dimension(39, 20));

        jtf_NazwaGracza4.setText("Gracz4");

        jcb_KolorGracza1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Czerwony", "Niebieski", "Zielony", "Żółty" }));

        jcb_KolorGracza2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Czerwony", "Niebieski", "Zielony", "Żółty" }));

        jcb_KolorGracza3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Czerwony", "Niebieski", "Zielony", "Żółty" }));

        jcb_KolorGracza4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Czerwony", "Niebieski", "Zielony", "Żółty" }));

        jb_StartGra.setText("Rozpocznij gre");
        jb_StartGra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_StartGraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_UstawieniaLayout = new javax.swing.GroupLayout(jp_Ustawienia);
        jp_Ustawienia.setLayout(jp_UstawieniaLayout);
        jp_UstawieniaLayout.setHorizontalGroup(
            jp_UstawieniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_UstawieniaLayout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addGroup(jp_UstawieniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jl_Ustawienia, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_UstawieniaLayout.createSequentialGroup()
                        .addComponent(jl_LiczbaGraczy, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(js_LiczbaGraczy, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_UstawieniaLayout.createSequentialGroup()
                        .addComponent(jtf_NazwaGracza1)
                        .addGap(10, 10, 10)
                        .addComponent(jcb_KolorGracza1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(jtf_NazwaGracza2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb_KolorGracza2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_UstawieniaLayout.createSequentialGroup()
                        .addComponent(jtf_NazwaGracza3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jcb_KolorGracza3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, 126)
                        .addComponent(jtf_NazwaGracza4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb_KolorGracza4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(380, 380, 380))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_UstawieniaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_StartGra, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(523, 523, 523))
        );
        jp_UstawieniaLayout.setVerticalGroup(
            jp_UstawieniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_UstawieniaLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jl_Ustawienia, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jp_UstawieniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_LiczbaGraczy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_LiczbaGraczy))
                .addGap(68, 68, 68)
                .addGroup(jp_UstawieniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_NazwaGracza1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_NazwaGracza2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_KolorGracza1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_KolorGracza2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jp_UstawieniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_NazwaGracza3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_NazwaGracza4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_KolorGracza3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_KolorGracza4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(jb_StartGra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(867, Short.MAX_VALUE))
        );

        jp_Start.setBackground(new java.awt.Color(0, 255, 0));
        jp_Start.setMinimumSize(new java.awt.Dimension(1280, 1024));
        jp_Start.setPreferredSize(new java.awt.Dimension(1280, 1024));

        jb_Start.setText("Start");
        jb_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_StartActionPerformed(evt);
            }
        });

        jb_Autorzy.setText("Autorzy");
        jb_Autorzy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_AutorzyActionPerformed(evt);
            }
        });

        jl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umonopoly/v2/logo.png"))); // NOI18N

        javax.swing.GroupLayout jp_StartLayout = new javax.swing.GroupLayout(jp_Start);
        jp_Start.setLayout(jp_StartLayout);
        jp_StartLayout.setHorizontalGroup(
            jp_StartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_StartLayout.createSequentialGroup()
                .addContainerGap(581, Short.MAX_VALUE)
                .addGroup(jp_StartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_StartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jb_Autorzy, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jb_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_StartLayout.createSequentialGroup()
                        .addComponent(jl_Logo)
                        .addGap(1, 1, 1)))
                .addGap(518, 518, 518))
        );
        jp_StartLayout.setVerticalGroup(
            jp_StartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_StartLayout.createSequentialGroup()
                .addContainerGap(376, Short.MAX_VALUE)
                .addComponent(jl_Logo)
                .addGap(75, 75, 75)
                .addComponent(jb_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_Autorzy, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_Start, javax.swing.GroupLayout.DEFAULT_SIZE, 1561, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp_Ustawienia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1561, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp_Gra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jp_Ustawienia, javax.swing.GroupLayout.DEFAULT_SIZE, 1401, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp_Gra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_zakonczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_zakonczActionPerformed
        jd_Autorzy.setVisible(false);
    }//GEN-LAST:event_jb_zakonczActionPerformed

    private void jb_AutorzyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_AutorzyActionPerformed
        jd_Autorzy.setVisible(true);
    }//GEN-LAST:event_jb_AutorzyActionPerformed

    private void jb_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_StartActionPerformed
        jp_Start.setVisible(false);
        jp_Ustawienia.setVisible(true);
        jcb_KolorGracza1.setVisible(true);
        jcb_KolorGracza2.setVisible(true);
        jtf_NazwaGracza3.setVisible(false);
        jtf_NazwaGracza4.setVisible(false);
        jcb_KolorGracza3.setVisible(false);
        jcb_KolorGracza4.setVisible(false);
        jb_StartGra.setVisible(true);
    }//GEN-LAST:event_jb_StartActionPerformed

    private void js_LiczbaGraczyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_js_LiczbaGraczyStateChanged
        if(Integer.parseInt(js_LiczbaGraczy.getValue().toString())<2)
        {
            js_LiczbaGraczy.setValue(2);
        }
        if (Integer.parseInt(js_LiczbaGraczy.getValue().toString())>4)
        {
            js_LiczbaGraczy.setValue(4);
        }
        if (Integer.parseInt(js_LiczbaGraczy.getValue().toString())==2)
        {
            jcb_KolorGracza3.setVisible(false);
            jcb_KolorGracza4.setVisible(false);
            jtf_NazwaGracza3.setVisible(false);
            jtf_NazwaGracza4.setVisible(false);
           
        }
        if (Integer.parseInt(js_LiczbaGraczy.getValue().toString())==3)
        {
            jcb_KolorGracza3.setVisible(true);
            jcb_KolorGracza4.setVisible(false);
            jtf_NazwaGracza3.setVisible(true);
            jtf_NazwaGracza4.setVisible(false);
            
        }
         if (Integer.parseInt(js_LiczbaGraczy.getValue().toString())==4)
        {
            
            jcb_KolorGracza4.setVisible(true);
            jtf_NazwaGracza4.setVisible(true);
          
        }
    }//GEN-LAST:event_js_LiczbaGraczyStateChanged

    private void jb_StartGraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_StartGraActionPerformed
       jp_Ustawienia.setVisible(false);
       jp_Gra.setVisible(true);
       jb_Eot.setEnabled(false);
        if(Integer.parseInt(js_LiczbaGraczy.getValue().toString())==2)
        {
            Vector <String> buff=new Vector<>();
            Vector <String> buff2=new Vector<>();
           
            buff.add(jtf_NazwaGracza1.getText());
            buff.add(jtf_NazwaGracza2.getText());
            buff2.add(jcb_KolorGracza1.getSelectedItem().toString());
            buff2.add(jcb_KolorGracza2.getSelectedItem().toString());
           
            
            silnik = new Engine((int)js_LiczbaGraczy.getValue(), buff, buff2);
            
            for(int x=0;x<silnik.getSizeOfPlayer();x++)
            {
                jta_Fundusze.setText(jta_Fundusze.getText()+silnik.getGracze(x).getName()+": "+silnik.getGracze(x).getMoney()+"$\n");
            }
            jtp_Log.setText(silnik.getLog());
            jl_AktywnyGracz.setText("Aktywny Gracz: "+silnik.getAktywnyPlayer().getName()+" "+silnik.getAktywnyPlayer().getMoney()+"$");
                    
        }
        if(Integer.parseInt(js_LiczbaGraczy.getValue().toString())==3)
        {
            Vector <String> buff=new Vector<>();
            Vector <String> buff2=new Vector<>();
           
            buff.add(jtf_NazwaGracza1.getText());
            buff.add(jtf_NazwaGracza2.getText());
            buff.add(jtf_NazwaGracza3.getText());
            buff2.add(jcb_KolorGracza1.getSelectedItem().toString());
            buff2.add(jcb_KolorGracza2.getSelectedItem().toString());
            buff2.add(jcb_KolorGracza3.getSelectedItem().toString());
           
            silnik = new Engine((int)js_LiczbaGraczy.getValue(), buff, buff2);
            
           
             for(int x=0;x<silnik.getSizeOfPlayer();x++)
            {
                jta_Fundusze.setText(jta_Fundusze.getText()+silnik.getGracze(x).getName()+": "+silnik.getGracze(x).getMoney()+"\n");
            }
             
             jtp_Log.setText(silnik.getLog());
             jl_AktywnyGracz.setText("Aktywny Gracz: "+silnik.getAktywnyPlayer().getName()+" "+silnik.getAktywnyPlayer().getMoney()+"$");
             
        }
        
        if(Integer.parseInt(js_LiczbaGraczy.getValue().toString())==4)
        {
            Vector <String> buff=new Vector<>();
            Vector <String> buff2=new Vector<>();
           
            buff.add(jtf_NazwaGracza1.getText());
            buff.add(jtf_NazwaGracza2.getText());
            buff.add(jtf_NazwaGracza3.getText());
            buff.add(jtf_NazwaGracza4.getText());
            buff2.add(jcb_KolorGracza1.getSelectedItem().toString());
            buff2.add(jcb_KolorGracza2.getSelectedItem().toString());
            buff2.add(jcb_KolorGracza3.getSelectedItem().toString());
            buff2.add(jcb_KolorGracza4.getSelectedItem().toString());
            
           
            silnik = new Engine((int)js_LiczbaGraczy.getValue(), buff, buff2);
            for(int x=0;x<silnik.getSizeOfPlayer();x++)
            {
                jta_Fundusze.setText(jta_Fundusze.getText()+silnik.getGracze(x).getName()+": "+silnik.getGracze(x).getMoney()+"\n");
            }
            jtp_Log.setText(silnik.getLog());
            jl_AktywnyGracz.setText("Aktywny Gracz: "+silnik.getAktywnyPlayer().getName()+" "+silnik.getAktywnyPlayer().getMoney()+"$");
            
        }
        
    }//GEN-LAST:event_jb_StartGraActionPerformed

    private void jb_RollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_RollActionPerformed
        jb_Roll.setEnabled(false);
        jb_Eot.setEnabled(true);
        silnik.random2k6();
        jtp_Log.setText(silnik.getLog());
        
        if(silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getOwner()!=10)
        {
        if (silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getOwner()==5)
        {
            jl_KupP.setText("Czy chcesz kupic " + silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getName()+"?");
            if(silnik.getAktywnyPlayer().getMoney()<silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getBuy_out())
            {
                jb_KupTak.setEnabled(false);
            }
            jd_KupP.setVisible(true);
            
        }
        
        if(silnik.getAktywnyPlayer().getId()==silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getOwner() && silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getHome()>0.0)
        {
            jl_KupD.setText("Czy chcesz kupic labolatrium na: "+silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getName()+" za "+silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getHome()+"?");
            jd_KupD.setVisible(true);
            if(silnik.getAktywnyPlayer().getMoney()<silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getHome())
            {
                jb_KupDTak.setEnabled(false);
            }
        
        }
        
        if (silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getOwner()!=silnik.getAktywnyPlayer().getId() && silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getOwner()!=5)
       {
            jd_Rachunek.setVisible(true);
            jta_Rachunek.setText("Od: "+silnik.getGracze(silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getOwner()).getName()+"\nDo: "+silnik.getAktywnyPlayer().getName()+"\nZa: "+silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getName()+"\nNależnosc: "+silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getKoszt()+"\nIlosc Labolatoriow:" + silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getDomki());
      }
        }
         jta_Fundusze.setText("");
            for(int x=0;x<silnik.getSizeOfPlayer();x++)
            {
                jta_Fundusze.setText(jta_Fundusze.getText()+silnik.getGracze(x).getName()+": "+silnik.getGracze(x).getMoney()+"$\n");
            }
         jl_AktywnyGracz.setText("Aktywny Gracz: "+silnik.getAktywnyPlayer().getName()+" "+silnik.getAktywnyPlayer().getMoney()+"$");
    }//GEN-LAST:event_jb_RollActionPerformed

    private void jb_EotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_EotActionPerformed
        jb_Roll.setEnabled(true);
        jb_Eot.setEnabled(false);
        silnik.koniecTury();
        jtp_Log.setText(silnik.getLog());
        jl_AktywnyGracz.setText("Aktywny Gracz: "+silnik.getAktywnyPlayer().getName()+" "+silnik.getAktywnyPlayer().getMoney()+"$");
    }//GEN-LAST:event_jb_EotActionPerformed

    private void jb_KupTakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_KupTakActionPerformed
        jd_KupP.setVisible(false);
        if (silnik.getAktywnyPlayer().getMoney()>silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getBuy_out())
        {
        silnik.getPole(silnik.getAktywnyPlayer().getWhere()).setOwner(silnik.getAktywnyPlayer().getId());
        silnik.getAktywnyPlayer().setMoney(silnik.getAktywnyPlayer().getMoney()-silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getBuy_out());
        silnik.getAktywnyPlayer().addToHand(silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getID());
        
        silnik.setLog(silnik.getLog()+"\n"+silnik.getAktywnyPlayer().getName()+" Kupil "+ silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getName());
        
        jl_AktywnyGracz.setText("Aktywny Gracz: "+silnik.getAktywnyPlayer().getName()+" "+silnik.getAktywnyPlayer().getMoney()+"$");
        jta_Fundusze.setText("");
        for(int x=0;x<silnik.getSizeOfPlayer();x++)
            {
                jta_Fundusze.setText(jta_Fundusze.getText()+silnik.getGracze(x).getName()+": "+silnik.getGracze(x).getMoney()+"$\n");
            }
        jtp_Log.setText(silnik.getLog());
        }
        else
        {
            jb_Error.setVisible(true);
        }
    }//GEN-LAST:event_jb_KupTakActionPerformed

    private void jb_KupNieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_KupNieActionPerformed
        jd_KupP.setVisible(false);
    }//GEN-LAST:event_jb_KupNieActionPerformed

    private void jb_KupDNieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_KupDNieActionPerformed
       jd_KupD.setVisible(false);
    }//GEN-LAST:event_jb_KupDNieActionPerformed

    private void jb_KupDTakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_KupDTakActionPerformed
        jd_KupD.setVisible(false);
        if (silnik.getAktywnyPlayer().getMoney()>silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getHome())
        {
            silnik.getPole(silnik.getAktywnyPlayer().getWhere()).setDomki(silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getDomki()+1);
            jl_AktywnyGracz.setText("Aktywny Gracz: "+silnik.getAktywnyPlayer().getName()+" "+silnik.getAktywnyPlayer().getMoney()+"$");
            silnik.getAktywnyPlayer().setMoney(silnik.getAktywnyPlayer().getMoney()-silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getHome());
            jta_Fundusze.setText("");
            for(int x=0;x<silnik.getSizeOfPlayer();x++)
            {
                jta_Fundusze.setText(jta_Fundusze.getText()+silnik.getGracze(x).getName()+": "+silnik.getGracze(x).getMoney()+"$\n");
            }
        }
        else
        {
            jb_Error.setVisible(true);
        }
    }//GEN-LAST:event_jb_KupDTakActionPerformed

    private void jb_ErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ErrorActionPerformed
        jb_Error.setVisible(false);
    }//GEN-LAST:event_jb_ErrorActionPerformed

    private void jb_ZaplacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ZaplacActionPerformed
        
            silnik.getAktywnyPlayer().setMoney(silnik.getAktywnyPlayer().getMoney()-silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getKoszt());
            silnik.getGracze(silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getOwner()).setMoney(silnik.getGracze(silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getOwner()).getMoney()+silnik.getPole(silnik.getAktywnyPlayer().getWhere()).getKoszt());
            jl_AktywnyGracz.setText("Aktywny Gracz: "+silnik.getAktywnyPlayer().getName()+" "+silnik.getAktywnyPlayer().getMoney()+"$");
            jta_Fundusze.setText("");
            for(int x=0;x<silnik.getSizeOfPlayer();x++)
            {
                jta_Fundusze.setText(jta_Fundusze.getText()+silnik.getGracze(x).getName()+": "+silnik.getGracze(x).getMoney()+"$\n");
            }
            jd_Rachunek.setVisible(false);
       
    }//GEN-LAST:event_jb_ZaplacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jb_Autorzy;
    private javax.swing.JButton jb_Eot;
    private javax.swing.JButton jb_Error;
    private javax.swing.JButton jb_KupDNie;
    private javax.swing.JButton jb_KupDTak;
    private javax.swing.JButton jb_KupNie;
    private javax.swing.JButton jb_KupTak;
    private javax.swing.JButton jb_Roll;
    private javax.swing.JButton jb_Start;
    private javax.swing.JButton jb_StartGra;
    private javax.swing.JButton jb_Zaplac;
    private javax.swing.JButton jb_zakoncz;
    private javax.swing.JComboBox<String> jcb_KolorGracza1;
    private javax.swing.JComboBox<String> jcb_KolorGracza2;
    private javax.swing.JComboBox<String> jcb_KolorGracza3;
    private javax.swing.JComboBox<String> jcb_KolorGracza4;
    private javax.swing.JDialog jd_Autorzy;
    private javax.swing.JDialog jd_Error;
    private javax.swing.JDialog jd_KupD;
    private javax.swing.JDialog jd_KupP;
    private javax.swing.JDialog jd_Rachunek;
    private javax.swing.JLabel jl_AktywnyGracz;
    private javax.swing.JLabel jl_Error;
    private javax.swing.JLabel jl_Fundusze;
    private javax.swing.JLabel jl_KupD;
    private javax.swing.JLabel jl_KupP;
    private javax.swing.JLabel jl_LiczbaGraczy;
    private javax.swing.JLabel jl_Logo;
    private javax.swing.JLabel jl_Logo2;
    private javax.swing.JLabel jl_Plansza;
    private javax.swing.JLabel jl_Rachunek;
    private javax.swing.JLabel jl_Ustawienia;
    private javax.swing.JLabel jl_autorzy;
    private javax.swing.JLabel jl_dawid;
    private javax.swing.JLabel jl_oskar;
    private javax.swing.JLabel jl_patryk;
    private javax.swing.JLabel jl_pawel;
    private javax.swing.JPanel jp_Gra;
    private javax.swing.JPanel jp_Plansza;
    private javax.swing.JPanel jp_Start;
    private javax.swing.JPanel jp_Ustawienia;
    private javax.swing.JSpinner js_LiczbaGraczy;
    private javax.swing.JTextArea jta_Fundusze;
    private javax.swing.JTextArea jta_Rachunek;
    private javax.swing.JTextField jtf_NazwaGracza1;
    private javax.swing.JTextField jtf_NazwaGracza2;
    private javax.swing.JTextField jtf_NazwaGracza3;
    private javax.swing.JTextField jtf_NazwaGracza4;
    private javax.swing.JTextPane jtp_Log;
    // End of variables declaration//GEN-END:variables
}
